spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:mysql://localhost:3306/twitterapp
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    ROOT: warn
