spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:mysql://localhost:3306/twitterapp
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        hdm2ddl:
          auto: update
  security:
    basic:
      enabled: false

spa:
  default-file:file:src/main/resources/public/index.html

logging:
  level:
    ROOT: warn
